# Copyright 2020-2025 Chris Croome
#
# This file is part of the Webarchitects MaxMind DB Apache Module Ansible role.
#
# The Webarchitects MaxMind DB Apache Module Ansible role is free software: you can redistribute it and/or modify it under the terms of the GNU General Public License as published by the Free Software Foundation, either version 3 of the License, or (at your option) any later version.
#
# The Webarchitects MaxMind DB Apache Module Ansible role is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License along with the Webarchitects MaxMind DB Apache Module Ansible role. If not, see <https://www.gnu.org/licenses/>.
---
- name: Check which version of MaxMind DB Apache Module is present
  block:

    - name: Strings from usr/lib/apache2/modules/mod_maxminddb.so
      ansible.builtin.shell: |
        set -e -o pipefail
        strings /usr/lib/apache2/modules/mod_maxminddb.so | grep /usr/local/src/mod_maxminddb
      args:
        executable: "{{  ansible_facts.ansible_local.bash.path }}"
      check_mode: false
      changed_when: false
      register: modmaxminddb_so_strings

    - name: Set a fact for the version of MaxMind DB Apache Module installed
      ansible.builtin.set_fact:
        modmaxminddb_installed: "{{ string | regex_replace('^/usr/local/src/mod_maxminddb-') | regex_replace('/src$') }}"
      when: ( "/usr/local/src/mod_maxminddb" in string )
      loop: "{{ modmaxminddb_so_strings.stdout_lines }}"
      loop_control:
        loop_var: string
        label: "{{ string }}"

  tags:
    - modmaxminddb
...
