---
- name: MaxMind DB Apache Module required packages present
  apt:
    pkg:
      - apache2-dev
      - libmaxminddb-dev
      - libmaxminddb0
      - libmmdb2-0
      - libmmdb2-dev
      - mmdb-bin
  tags:
    - modmaxminddb

- name: Check if MaxMind DB Apache Module is present
  stat:
    path: /usr/lib/apache2/modules/mod_maxminddb.so
  register: modmaxminddb_so
  tags:
    - modmaxminddb

- name: Check which version of MaxMind DB Apache Module is present
  include_tasks: check.yml
  when: ( modmaxminddb_so is defined ) and ( modmaxminddb_so.stat.exists )
  tags:
    - modmaxminddb

- name: Check the latest version of MaxMind DB Apache Module
  include_tasks: latest.yml
  tags:
    - modmaxminddb

- name: Download and install MaxMind DB Apache Module
  include_tasks: install.yml
  when: ( modmaxminddb_so is defined ) and ( modmaxminddb_so.stat.exists == False ) or ( modmaxminddb_installed is defined ) and ( modmaxminddb_installed != modmaxminddb_latest )
  tags:
    - modmaxminddb
...
